# config/services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
      - "../src/Migrations/"

  # Explicit configuration for Messenger
  App\Message\:
    resource: "../src/Message/"
    tags: ["messenger.message"]

  App\MessageHandler\:
    resource: "../src/MessageHandler/"
    tags: ["messenger.message_handler"]
